### ISSUE TITLE
Make the adapter work with RESTAdapter

### ISSUE THREAD

**Issue by fsmanuel** [funkensturm/ember-local-storage#28]
- [ ] Make it work with RESTAdapter

**Comment by marcemira** [comment]
Any news on this?

**Comment by fsmanuel** [comment]
@marcemira i have decided to not support the RESTAdapter because I have no use case for it. The JSONApiAdapter is around for some time and only apps stuck on 1.2 can not use the addon.
Tell me about your use case maybe I missed some important facts.

**Comment by marcemira** [comment]
Hello @fsmanuel, thanks for answering. My use case is the following:
I currently have a set of models that repeats a lot of request to my API during the natural flow of the application, like category, sub-categories, countries, user common information like genders and others. These are mostly static, but some might change from times to times. So, in order to leverage these amount of requests, I decided to give this addon a try and have it load(import) my payloads and use it instead of http Requests. The problem is that my API is still RESTful and the importData method will only accept JSON API documents (hash or string) as parameter. Then, I was asking to support this kind of payload, same as JSON API complaints. I spent half a day trying to have the RESTSerializer to somehow convert it, with no luck so far. Do you think is difficult to support it? If so, ca you provide me some short guidance so I can try to implement it on a fork of mine? Thank you for your time. Awesome work btw :+1:

**Comment by fsmanuel** [comment]
@marcemira thanks for the flowers and feedback. Interesting approach to use `importData`. The import/export are precisely the reason why I don't want to support the RESTSerializer. I don't want to maintain all the conversion.
Try to use your code above but do not use `_normalizeResponse` and instead use [`normalizeResponse`](http://emberjs.com/api/data/classes/DS.Serializer.html#method_normalizeResponse) that should do the work you need to convert the REST payload to a JSON API Document.

**Comment by marcemira** [comment]
@fsmanuel thanks for answering, I was just tracing the code while the serializer performs the normalizeResult with a normal model and with the ones I intent to use with ember-local-storage serializer and I found out that [this line on rest serializer](https://github.com/emberjs/data/blob/2322aacc3f3e4fb4fe9b30c7d790c45126fa5c73/addon/serializers/rest.js#L184) will use `ember-local-storage/serializers/serializer`(which extends from JSONSerializer) hence beeing unable to do the actual conversion, resultin on an error T__T. Do you think of any way I can sort this? If not, I would just fork your addon and try to support RESTSerializer hehe. Thanks again

**Comment by fsmanuel** [comment]
Ah I see, the model lookup will not work.

Concerning your update. JSONAPI payload expects a data property that's why it looks for a model data. In your fork you have to change the _handleRequest resolve payload to make it work.

If you can put up a PR that handles both REST and JSONAPI I'm happy to merge! Anyway link to your solution maybe we can figure out how to support both.

I also thought about something similar to your approach that switches to localStorage if the user is offline and to a backend adapter if the user is online. But it's not trivial to do the sync of created, updated or deleted records if the user went online...
