### ISSUE TITLE
How to use in multiple controllers?

### ISSUE THREAD

**Issue by graup** [funkensturm/ember-local-storage#36]
Hi! I've run into a problem using the local-storage modal I created with this in multiple locations. I suppose that when using `create()` it creates a new object instance for every controller it is used in – if I change the content in one controller now, how can I get these changes in another one?

I'm trying to make a history of objects the user viewed. The detail page will add an entry to the local storage object, which should be displayed on the start page.

**Comment by fsmanuel** [comment]
Hey @graup there are different ways to achieve that:

1. You can `create()` in the module:
```js
import StorageArray from 'ember-local-storage/local/array';
export default StorageArray.create({
  storageKey: 'object-views'
});
```
and import the instance in every controller you need.

2. You can use `inject.controller()` and `computed.alias` to connect your controllers.

3. You can use a service that handles the instance and inject it wherever you need it. I would recommend that option because it's more Ember 2.0 and you can add more logic in that service if you need.

**Comment by graup** [comment]
Thanks, that was very helpful! I went and added a service that keeps its own instance of a StorageArray.

**Comment by fsmanuel** [comment]
Perfect!
I guess it should be possible to make the service itself a `StorageArray` but I haven't tested it and I don't know if it's a good idea. It would be:

```js
// app/services/object-views.js
import Ember from 'ember';
import ArrayProxyMixin from 'ember-local-storage/mixins/array';

export default Ember.Service.extend(ArrayProxyMixin, {
  _storage: 'local',
  storageKey: 'object-views'
});
```
