### ISSUE TITLE
Adapter Querying

### ISSUE THREAD

**Issue by mattcroberts** [funkensturm/ember-local-storage#38]
I've just started using this addon for localstorage and it seems to work great however it looks as though querying has not been implemented. Is this correct? Is there a way to get it to work?

To be clear what I am trying to achieve is

```
this.store.query('myModel', {
   userId: '123'
})
```

However it is returning all models for that type.

Thanks,
Matt

**Comment by fsmanuel** [comment]
Hey @mattcroberts great to hear that it works.
Querying is not implemented yet. I'll implement it and let you know when I'm done.

**Comment by mattcroberts** [comment]
Thanks!

**Comment by robbiespeed** [comment]
@fsmanuel I created a pull request with potential implementation https://github.com/funkensturm/ember-local-storage/pull/39. Sorry if you already started working on it, I just needed to get it working for one of my projects. Haven't run into any issues yet with it. If you'd like I could see about adding support for pagination, and sort as well, though I don't have much use for them yet.

**Comment by fsmanuel** [comment]
@robbiespeed thanks for the PR. I commented on the PR to figure out what features you need.
To cover the use case of @mattcroberts we need the filter the relationships as well. I'm almost finished with the implementation.

Do we need [`queryRecord`](http://emberjs.com/api/data/classes/DS.Store.html#method_queryRecord)?

I guess pagination isn't required because we are local and folks can use [ember-cli-pagination](https://github.com/mharris717/ember-cli-pagination).

**Comment by fsmanuel** [comment]
@mattcroberts i released 0.1.0 with a query implementation. see the [readme](https://github.com/funkensturm/ember-local-storage#query--queryrecord)

@robbiespeed thanks again for pairing and reviewing.

**Comment by robbiespeed** [comment]
@fsmanuel not a problem, glad to see it turn into such a great implementation of filter querying.
